# Generated by Django 4.1.7 on 2023-04-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardimage',
            name='board',
        ),
        migrations.AddField(
            model_name='boardimage',
            name='image_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='boardimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
