# Generated by Django 4.1.7 on 2023-04-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_boardimage_board_boardimage_image_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimage',
            name='image_title',
            field=models.CharField(max_length=200),
        ),
    ]
